openapi: 3.1.0
info:
  title: Pteron Public API
  version: 1.0.0
  description: |
    プロジェクト開発者向けの外部公開API。
    アクセストークンによるBearer認証が必要。
servers:
  - url: /api/v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        balance:
          type: integer
          format: int64

    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: integer
          format: int64
        type:
          type: string
          enum: [TRANSFER, BILL_PAYMENT]
          description: |
            取引の種類
            - TRANSFER: プロジェクトからユーザーへの送金 (Project -> User)
            - BILL_PAYMENT: プロジェクトへの請求の支払い (User -> Project)
        user_id:
          type: string
          format: uuid
          description: 取引相手のユーザーID (UUID)
        user_name:
          type: string
          description: 取引相手のユーザー名 (traP ID)
        project_id:
          type: string
          format: uuid
        description:
          type: string
        created_at:
          type: string
          format: date-time

    Bill:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: integer
          format: int64
        user_id:
          type: string
          format: uuid
          description: 請求対象のユーザーID (UUID)
        user_name:
          type: string
          description: 請求対象のユーザー名 (traP ID)
        description:
          type: string
        status:
          type: string
          enum: [PENDING, COMPLETED, REJECTED, FAILED]
        created_at:
          type: string
          format: date-time

    # Request/Response Schemas
    CreateTransactionRequest:
      type: object
      required:
        - to_user
        - amount
      properties:
        to_user:
          type: string
          description: 送金先のユーザー名 (traP ID)
        amount:
          type: integer
          format: int64
          minimum: 1
        description:
          type: string
        request_id:
          type: string
          format: uuid
          description: 冪等性キー (必須推奨)

    CreateBillRequest:
      type: object
      required:
        - target_user
        - amount
        - success_url
        - cancel_url
      properties:
        target_user:
          type: string
          description: 請求先のユーザー名 (traP ID)
        amount:
          type: integer
          format: int64
          minimum: 1
        description:
          type: string
        success_url:
          type: string
          format: uri
          description: 決済成功時のリダイレクト先URL
        cancel_url:
          type: string
          format: uri
          description: 決済キャンセル/拒否時のリダイレクト先URL

    CreateBillResponse:
      type: object
      properties:
        bill_id:
          type: string
          format: uuid
        payment_url:
          type: string
          format: uri
          description: ユーザーをリダイレクトさせる決済確認ページのURL
        expires_at:
          type: string
          format: date-time

security:
  - BearerAuth: []

paths:
  # --- Project ---
  /project:
    get:
      tags: [Project]
      summary: 自プロジェクトの情報を取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

  /project/transactions:
    get:
      tags: [Project]
      summary: 取引履歴を取得
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          schema:
            type: string
            description: |
              続きを取得するためのカーソル
              前回のレスポンスの next_cursor に含まれる値を指定します。
              初回リクエスト時は未指定とします。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: [items]
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  next_cursor:
                    type: string
                    description: 次のページを取得するためのカーソル (存在しない場合は未設定)

  # --- Transactions ---
  /transactions:
    post:
      tags: [Transactions]
      summary: ユーザーへ送金する (配布・賞与など)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        '200':
          description: 送金成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: 残高不足など

  # --- Bills ---
  /bills:
    post:
      tags: [Bills]
      summary: ユーザーへの請求を作成する
      description: レスポンスに含まれる payment_url へユーザーを誘導してください
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBillRequest'
      responses:
        '201':
          description: 請求作成完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBillResponse'

  /bills/{bill_id}:
    get:
      tags: [Bills]
      summary: 請求のステータスを確認する
      parameters:
        - name: bill_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
