# Type: どのような種類であるか
- name: "type/enhancement"
  color: "007bff"
  description: "新機能の追加や既存機能の改善"
- name: "type/bug"
  color: "d73a4a"
  description: "期待通りに動作しない不具合"
- name: "type/refactoring"
  color: "6f42c1"
  description: "コード品質を向上させる内部改善"
- name: "type/chore"
  color: "6a737d"
  description: "保守や設定の変更等の作業"

# Area: どこを/何を触るか
- name: "area/client"
  color: "28a745"
  description: "フロントエンド関連"
- name: "area/server"
  color: "1d76db"
  description: "一般的なサーバー関連"
- name: "area/server-finance"
  color: "0e2a47"
  description: "金融サーバー関連"
- name: "area/infra"
  color: "8B4513"
  description: "Docker/CI/CD関連"
- name: "area/design"
  color: "db61a2"
  description: "UI/UXデザイン関連"
- name: "area/docs"
  color: "cfd8dc"
  description: "ドキュメント関連"

# Priority: 優先度
- name: "priority/critical"
  color: "b60205"
  description: "最優先で対応すべき"
- name: "priority/must"
  color: "fbca04"
  description: "リリースに必須"
- name: "priority/should"
  color: "fef2c0"
  description: "対応が推奨される改善"
- name: "priority/could"
  color: "f7f7f7"
  description: "必須ではない改善"

# Need: 必要なアクションや状態
- name: "need/attention"
  color: "ffc107"
  description: "慎重な作業やレビューが必要"
- name: "need/triage"
  color: "FF9800"
  description: "状況整理や優先度の判定が必要"
- name: "need/discussion"
  color: "84DEFF"
  description: "仕様や方針の議論が必要"
- name: "need/help"
  color: "0E8A16"
  description: "助けが必要な状態"

# Status: 課題の状態
- name: "status/blocked"
  color: "E11D21"
  description: "外部要因や依存関係により進行不可"
- name: "status/invalid"
  color: "CFD3D7"
  description: "誤報、再現できない、仕様通りなど無効と判断されるケース"
